// Discover module data for Preparation AI.
// 33 items across 4 categories: Courses (12), Internships (8), Govt (7), Short (6).
// Real programmes / internships / schemes / certifications with rich metadata
// for the Discover page. Apply links are Google Search URLs (safe fallback).

export type DiscoverCategory = 'Courses' | 'Internships' | 'Govt' | 'Short';
export type DiscoverAccent = 'blue' | 'gold';

export interface DiscoverItem {
  id: string;
  title: string;
  category: DiscoverCategory;
  /** Compact field label shown as a top-right chip (e.g. "Cybersecurity"). */
  fieldBadge: string;
  /** High-level demand label: 'Very High' / 'High' / 'Medium' / 'Emerging'. */
  demand: 'Very High' | 'High' | 'Medium' | 'Emerging';
  /** One-line elevator pitch. */
  description: string;
  /** Salary / stipend range as displayed (currency-agnostic strings). */
  salaryRange: string;
  /** Growth narrative: e.g. "+22% by 2030". */
  growthTrend: string;
  /** Accent color used for left bars and badges. */
  accentColor: DiscoverAccent;
  /** Career outcomes (job titles one can pursue). */
  careerOutcomes: string[];
  /** Salary progression milestones at different career stages. */
  salaryProgression: { stage: string; salary: string }[];
  /** Notable institutions / providers / companies offering this. */
  institutions: string[];
  /** Titles of similar/related items. */
  similarCourses: string[];
  /** Duration label, if applicable (e.g. "4 years"). */
  duration?: string;
  /** Provider / awarding body, if applicable (e.g. "NPTEL / IIT Madras"). */
  provider?: string;
  /** Cost label, if applicable (e.g. "Free", "₹2,000", "$49"). */
  cost?: string;
  /** Eligibility text, if applicable. */
  eligibility?: string;
  /** Skills covered (for courses / short certs). */
  skillsCovered?: string[];
  /** Google Search URL with the title as the query. */
  applyLink: string;
  /** Grades this item is suitable for. */
  grades: string[];
}

// Helper: returns a Google Search URL for a query.
function search(query: string): string {
  return `https://www.google.com/search?q=${encodeURIComponent(query)}`;
}

// Grades available on the Discover page selector (Class 8 → Graduate).
export const DISCOVER_GRADES: { value: string; label: string }[] = [
  { value: 'class-8', label: 'Class 8' },
  { value: 'class-9', label: 'Class 9' },
  { value: 'class-10', label: 'Class 10' },
  { value: 'class-11', label: 'Class 11' },
  { value: 'class-12', label: 'Class 12' },
  { value: 'graduate', label: 'Graduate' },
];

export const DISCOVER_ITEMS: DiscoverItem[] = [
  // ============ COURSES (12) ============
  {
    id: 'btech-cse',
    title: 'B.Tech Computer Science Engineering',
    category: 'Courses',
    fieldBadge: 'Software',
    demand: 'Very High',
    description:
      '4-year undergraduate degree covering algorithms, software engineering, AI/ML, databases, and system design. Gateway to product, research, and entrepreneurship careers.',
    salaryRange: '₹6-25 LPA (fresher) · ₹20-80 LPA (mid)',
    growthTrend: '+23% software roles by 2032 (US BLS)',
    accentColor: 'blue',
    careerOutcomes: ['Software Engineer', 'ML Engineer', 'Product Manager', 'CTO', 'Founder'],
    salaryProgression: [
      { stage: 'Fresher (0-2 yrs)', salary: '₹6-12 LPA' },
      { stage: 'Mid (3-6 yrs)', salary: '₹18-35 LPA' },
      { stage: 'Senior (7-12 yrs)', salary: '₹40-80 LPA' },
      { stage: 'Staff/Lead (12+ yrs)', salary: '₹80L-2 Cr' },
    ],
    institutions: ['IIT Bombay', 'IIT Delhi', 'BITS Pilani', 'IIIT Hyderabad', 'NIT Trichy'],
    similarCourses: ['B.Tech Electronics & Communication', 'B.Sc Computer Science', 'BCA Data Science'],
    duration: '4 years',
    eligibility: 'Class 12 with Physics, Chemistry, Mathematics; JEE Main / BITSAT / state CET',
    skillsCovered: ['Data Structures', 'Algorithms', 'Operating Systems', 'DBMS', 'Machine Learning', 'Cloud Computing'],
    applyLink: search('B.Tech Computer Science Engineering India admission'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'ethical-hacking',
    title: 'Ethical Hacking & Cybersecurity',
    category: 'Courses',
    fieldBadge: 'Cybersecurity',
    demand: 'Very High',
    description:
      'Diploma / certification programme on penetration testing, network defense, OWASP Top 10, and incident response. Includes hands-on labs in controlled cyber ranges.',
    salaryRange: '₹5-18 LPA (fresher) · ₹25-60 LPA (mid)',
    growthTrend: '+32% cybersecurity jobs by 2032',
    accentColor: 'blue',
    careerOutcomes: ['Penetration Tester', 'Security Analyst', 'SOC Engineer', 'Chief Information Security Officer'],
    salaryProgression: [
      { stage: 'Junior Analyst (0-2 yrs)', salary: '₹5-9 LPA' },
      { stage: 'Pen Tester (3-5 yrs)', salary: '₹12-22 LPA' },
      { stage: 'Senior Security Engineer', salary: '₹25-45 LPA' },
      { stage: 'CISO', salary: '₹60L-2 Cr' },
    ],
    institutions: ['IIT Madras (NPTEL)', 'EC-Council', 'Offensive Security', 'CDAC', 'Coursera'],
    similarCourses: ['B.Tech CSE', 'Network Forensics', 'Cloud Security Certificate'],
    duration: '6-12 months',
    provider: 'EC-Council / NPTEL / CDAC',
    cost: '₹15,000 - ₹80,000',
    eligibility: 'Class 12 with basic programming; some prior networking knowledge preferred',
    skillsCovered: ['Kali Linux', 'Nmap', 'Metasploit', 'OWASP ZAP', 'Burp Suite', 'Incident Response'],
    applyLink: search('Ethical Hacking certification course CEH'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'space-law',
    title: 'Space Law & Policy',
    category: 'Courses',
    fieldBadge: 'Aerospace Law',
    demand: 'Emerging',
    description:
      'Postgraduate / certificate programme covering UN space treaties, satellite regulation, launch licensing, asteroid mining rights, and the commercial space economy.',
    salaryRange: '₹8-20 LPA (India) · $80K-$180K (global)',
    growthTrend: 'Global space economy $1T by 2040 (Morgan Stanley)',
    accentColor: 'gold',
    careerOutcomes: ['Space Policy Analyst', 'Satellite Regulatory Counsel', 'ISRO Legal Officer', 'Space Insurance Underwriter'],
    salaryProgression: [
      { stage: 'Junior Analyst (0-2 yrs)', salary: '₹6-12 LPA' },
      { stage: 'Associate (3-6 yrs)', salary: '₹15-28 LPA' },
      { stage: 'Senior Counsel', salary: '₹30-60 LPA' },
      { stage: 'Partner / Director', salary: '₹60L-1.5 Cr' },
    ],
    institutions: ['NALSAR Hyderabad', 'GNLU Gandhinagar', 'Leiden University (NL)', 'ISPL Bangalore'],
    similarCourses: ['International Law', 'Aviation Law', 'Telecom Regulation'],
    duration: '1-2 years',
    provider: 'NALSAR / GNLU',
    cost: '₹50,000 - ₹2,00,000',
    eligibility: 'Bachelor in Law (LL.B.) or related field; some certificate courses open to Class 12 grads',
    skillsCovered: ['Outer Space Treaty', 'ITU Regulations', 'Launch Licensing', 'Satcom Policy', 'Space Insurance'],
    applyLink: search('Space Law and Policy course India NALSAR'),
    grades: ['class-12', 'graduate'],
  },
  {
    id: 'marine-biology',
    title: 'Marine Biology & Oceanography',
    category: 'Courses',
    fieldBadge: 'Ocean Science',
    demand: 'High',
    description:
      'Undergraduate + postgraduate programme studying marine ecosystems, coral reefs, deep-sea biology, fisheries, and climate change impact on oceans. Includes field work at sea.',
    salaryRange: '₹4-12 LPA (fresher) · ₹15-35 LPA (mid)',
    growthTrend: '+5% biodiversity & ocean research jobs by 2030',
    accentColor: 'blue',
    careerOutcomes: ['Marine Biologist', 'Oceanographer', 'Fisheries Scientist', 'Conservation Officer'],
    salaryProgression: [
      { stage: 'Research Assistant (0-2 yrs)', salary: '₹4-7 LPA' },
      { stage: 'Marine Biologist (3-6 yrs)', salary: '₹8-15 LPA' },
      { stage: 'Senior Scientist', salary: '₹18-30 LPA' },
      { stage: 'Director / Professor', salary: '₹35-60 LPA' },
    ],
    institutions: ['Cochin University of Science & Technology', 'Annamalai University', 'IIT Madras (Ocean Engg)', 'Woods Hole (USA)'],
    similarCourses: ['B.Sc Environmental Science', 'Aquaculture', 'Marine Engineering'],
    duration: '3-5 years',
    eligibility: 'Class 12 with Biology; NEET or university-specific entrance',
    skillsCovered: ['Marine Ecology', 'Coral Reef Studies', 'Plankton Analysis', 'Scuba Diving', 'Biostatistics', 'GIS Mapping'],
    applyLink: search('Marine Biology undergraduate course India'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'btech-mechanical',
    title: 'B.Tech Mechanical Engineering',
    category: 'Courses',
    fieldBadge: 'Manufacturing',
    demand: 'High',
    description:
      'Foundational 4-year engineering degree in design, thermodynamics, manufacturing, robotics, and CAD/CAM. Critical for EV, aerospace, and Industry 4.0.',
    salaryRange: '₹4-12 LPA (fresher) · ₹15-40 LPA (mid)',
    growthTrend: '+1.5M jobs globally in EV manufacturing by 2030',
    accentColor: 'gold',
    careerOutcomes: ['Design Engineer', 'Manufacturing Engineer', 'EV Powertrain Engineer', 'Plant Head'],
    salaryProgression: [
      { stage: 'GET (0-2 yrs)', salary: '₹4-7 LPA' },
      { stage: 'Design Engineer (3-6 yrs)', salary: '₹10-18 LPA' },
      { stage: 'Senior Engineer', salary: '₹18-35 LPA' },
      { stage: 'Plant Head / CTO', salary: '₹40L-1.5 Cr' },
    ],
    institutions: ['IIT Madras', 'IIT Bombay', 'BITS Pilani', 'VIT Vellore', 'NIT Surathkal'],
    similarCourses: ['B.Tech Mechatronics', 'B.Tech Automobile', 'B.Tech Manufacturing'],
    duration: '4 years',
    eligibility: 'Class 12 PCM; JEE Main / BITSAT / state CET',
    skillsCovered: ['SolidWorks', 'CATIA', 'Thermodynamics', 'Robotics', 'FEA', 'Manufacturing Processes'],
    applyLink: search('B.Tech Mechanical Engineering India admission JEE'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'mbbs',
    title: 'MBBS (Bachelor of Medicine, Bachelor of Surgery)',
    category: 'Courses',
    fieldBadge: 'Medicine',
    demand: 'Very High',
    description:
      '5.5-year undergraduate medical degree (incl. 1-year internship). Foundations in anatomy, physiology, pathology, pharmacology, and clinical practice.',
    salaryRange: '₹6-15 LPA (junior) · ₹15-50 LPA (specialist)',
    growthTrend: 'India needs 2M+ more doctors by 2030 (WHO)',
    accentColor: 'blue',
    careerOutcomes: ['General Physician', 'Surgeon', 'Pediatrician', 'Cardiologist', 'Medical Officer'],
    salaryProgression: [
      { stage: 'Intern (1 yr)', salary: '₹3-6 LPA' },
      { stage: 'Junior Resident (1-3 yrs)', salary: '₹8-14 LPA' },
      { stage: 'Senior Resident (3-6 yrs)', salary: '₹14-25 LPA' },
      { stage: 'Consultant Specialist', salary: '₹25-80 LPA' },
    ],
    institutions: ['AIIMS Delhi', 'CMC Vellore', 'AFMC Pune', 'JIPMER Puducherry', 'MAMC Delhi'],
    similarCourses: ['BDS Dentistry', 'BAMS Ayurveda', 'B.Sc Nursing'],
    duration: '5.5 years',
    eligibility: 'Class 12 PCB with NEET qualification',
    skillsCovered: ['Anatomy', 'Physiology', 'Pathology', 'Pharmacology', 'Surgery', 'Community Medicine'],
    applyLink: search('MBBS admission India NEET'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'ba-llb',
    title: 'B.A. LL.B. (5-Year Integrated Law)',
    category: 'Courses',
    fieldBadge: 'Law',
    demand: 'High',
    description:
      'Integrated undergraduate law degree blending humanities + legal studies. Covers constitutional, criminal, corporate, and cyber law. Gateway to litigation, judiciary, and corporate counsel.',
    salaryRange: '₹5-15 LPA (fresher) · ₹20-60 LPA (mid)',
    growthTrend: '+9% legal services growth through 2030',
    accentColor: 'gold',
    careerOutcomes: ['Advocate', 'Corporate Counsel', 'Judge', 'Legal Advisor', 'Public Prosecutor'],
    salaryProgression: [
      { stage: 'Junior Associate (0-2 yrs)', salary: '₹5-9 LPA' },
      { stage: 'Associate (3-5 yrs)', salary: '₹12-20 LPA' },
      { stage: 'Senior Associate', salary: '₹25-45 LPA' },
      { stage: 'Partner', salary: '₹60L-2 Cr' },
    ],
    institutions: ['NLSIU Bangalore', 'NALSAR Hyderabad', 'NLU Delhi', 'WBNUJS Kolkata', 'Symbiosis Law School'],
    similarCourses: ['LL.B. (3-year)', 'BBA LL.B.', 'Cyber Law Diploma'],
    duration: '5 years',
    eligibility: 'Class 12 with CLAT / AILET / LSAT-India',
    skillsCovered: ['Constitutional Law', 'Criminal Law', 'Corporate Law', 'Cyber Law', 'Contract Law', 'Moot Court'],
    applyLink: search('BA LLB integrated law course CLAT India'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'bdes-uxui',
    title: 'Bachelor of Design (UX/UI)',
    category: 'Courses',
    fieldBadge: 'Design',
    demand: 'High',
    description:
      '4-year design degree focusing on user research, interaction design, prototyping, and visual systems. Bridges psychology, technology, and aesthetics.',
    salaryRange: '₹5-14 LPA (fresher) · ₹18-45 LPA (mid)',
    growthTrend: '+13% UX design jobs through 2030',
    accentColor: 'blue',
    careerOutcomes: ['UX Designer', 'Product Designer', 'Design Lead', 'UX Researcher'],
    salaryProgression: [
      { stage: 'Junior Designer (0-2 yrs)', salary: '₹5-9 LPA' },
      { stage: 'Product Designer (3-5 yrs)', salary: '₹12-22 LPA' },
      { stage: 'Senior Designer', salary: '₹22-40 LPA' },
      { stage: 'Design Director', salary: '₹40L-1 Cr' },
    ],
    institutions: ['NID Ahmedabad', 'IIT Bombay (IDC)', 'MIT Institute of Design', 'Srishti Bangalore', 'Pearl Academy'],
    similarCourses: ['B.Des Graphic Design', 'B.Sc Animation', 'Interaction Design Master'],
    duration: '4 years',
    eligibility: 'Class 12 (any stream); NID DAT / UCEED / institute entrance',
    skillsCovered: ['Figma', 'User Research', 'Wireframing', 'Prototyping', 'Design Systems', 'Accessibility'],
    applyLink: search('Bachelor of Design UX UI India UCEED NID'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'bsc-biotech',
    title: 'B.Sc Biotechnology',
    category: 'Courses',
    fieldBadge: 'Bio-Science',
    demand: 'High',
    description:
      '3-year undergraduate degree combining biology + technology for healthcare, agriculture, and industrial applications. Covers genetic engineering, bioinformatics, and fermentation tech.',
    salaryRange: '₹3-9 LPA (fresher) · ₹12-28 LPA (mid)',
    growthTrend: '+17% biotech industry CAGR globally',
    accentColor: 'blue',
    careerOutcomes: ['Research Associate', 'Bioinformatician', 'Biotech Engineer', 'Quality Analyst'],
    salaryProgression: [
      { stage: 'Research Asst (0-2 yrs)', salary: '₹3-6 LPA' },
      { stage: 'Scientist (3-5 yrs)', salary: '₹8-15 LPA' },
      { stage: 'Senior Scientist', salary: '₹15-30 LPA' },
      { stage: 'R&D Head', salary: '₹30-60 LPA' },
    ],
    institutions: ['IIT Madras (BS)', 'AIIMS', 'University of Hyderabad', 'JNU', 'TIFR'],
    similarCourses: ['B.Sc Genetics', 'B.Sc Microbiology', 'B.Tech Biotech'],
    duration: '3 years',
    eligibility: 'Class 12 PCB / PCM; institute entrance (JEE / CUET)',
    skillsCovered: ['Genetic Engineering', 'PCR', 'Cell Culture', 'Bioinformatics', 'Bio-statistics', 'CRISPR basics'],
    applyLink: search('B.Sc Biotechnology India admission CUET'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'bba',
    title: 'BBA (Bachelor of Business Administration)',
    category: 'Courses',
    fieldBadge: 'Management',
    demand: 'High',
    description:
      '3-year undergraduate management degree covering marketing, finance, HR, and operations. Foundational pathway for MBA and entrepreneurship.',
    salaryRange: '₹3-8 LPA (fresher) · ₹12-25 LPA (post-MBA)',
    growthTrend: '+8% management consulting roles through 2030',
    accentColor: 'gold',
    careerOutcomes: ['Management Trainee', 'Business Analyst', 'Marketing Executive', 'Entrepreneur'],
    salaryProgression: [
      { stage: 'Trainee (0-2 yrs)', salary: '₹3-6 LPA' },
      { stage: 'Analyst (3-5 yrs)', salary: '₹7-14 LPA' },
      { stage: 'Manager', salary: '₹14-28 LPA' },
      { stage: 'Director / VP', salary: '₹30-80 LPA' },
    ],
    institutions: ['IIM Indore (IPM)', 'Shaheed Sukhdev College Delhi', 'NMIMS Mumbai', 'Christ University', 'Symbiosis'],
    similarCourses: ['B.Com', 'BMS', 'Integrated MBA (IPM)'],
    duration: '3 years',
    eligibility: 'Class 12 (any stream); institute entrance (IPMAT / NPAT / SET)',
    skillsCovered: ['Marketing', 'Financial Accounting', 'Operations', 'HRM', 'Business Strategy', 'Statistics'],
    applyLink: search('BBA admission India IPMAT NPAT'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'ba-economics',
    title: 'B.A. (Hons) Economics',
    category: 'Courses',
    fieldBadge: 'Economics',
    demand: 'High',
    description:
      '3-year undergraduate degree in micro/macro economics, econometrics, and development economics. Pathway to RBI, public policy, finance, and consulting.',
    salaryRange: '₹5-12 LPA (fresher) · ₹15-40 LPA (mid)',
    growthTrend: '+14% economist & policy jobs through 2030',
    accentColor: 'gold',
    careerOutcomes: ['Economist', 'Policy Analyst', 'Investment Banker', 'Data Analyst', 'Civil Servant'],
    salaryProgression: [
      { stage: 'Research Analyst (0-2 yrs)', salary: '₹5-9 LPA' },
      { stage: 'Associate (3-5 yrs)', salary: '₹10-20 LPA' },
      { stage: 'Senior Economist', salary: '₹22-40 LPA' },
      { stage: 'Chief Economist', salary: '₹50L-2 Cr' },
    ],
    institutions: ['St. Stephens Delhi', 'Delhi School of Economics', 'LSE (UK)', 'ISI Kolkata', 'Ashoka University'],
    similarCourses: ['B.Com Hons', 'B.A. Statistics', 'B.Sc Finance'],
    duration: '3 years',
    eligibility: 'Class 12 with Mathematics (preferred); CUET / institute entrance',
    skillsCovered: ['Microeconomics', 'Macroeconomics', 'Econometrics', 'Statistics', 'R / Python', 'Public Policy'],
    applyLink: search('BA Hons Economics admission India CUET'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'barch',
    title: 'B.Arch (Bachelor of Architecture)',
    category: 'Courses',
    fieldBadge: 'Architecture',
    demand: 'Medium',
    description:
      '5-year undergraduate degree in architectural design, building systems, urban planning, and sustainable construction. Blends art, engineering, and sustainability.',
    salaryRange: '₹4-10 LPA (fresher) · ₹12-30 LPA (mid)',
    growthTrend: '+3% architecture jobs globally through 2030',
    accentColor: 'blue',
    careerOutcomes: ['Architect', 'Urban Planner', 'Landscape Architect', 'Project Manager', 'Sustainability Consultant'],
    salaryProgression: [
      { stage: 'Junior Architect (0-2 yrs)', salary: '₹4-7 LPA' },
      { stage: 'Project Architect (3-6 yrs)', salary: '₹9-16 LPA' },
      { stage: 'Senior Architect', salary: '₹16-30 LPA' },
      { stage: 'Principal / Partner', salary: '₹30-60 LPA' },
    ],
    institutions: ['SPA Delhi', 'IIT Kharagpur', 'IIT Roorkee', 'CEPT Ahmedabad', 'Manipal'],
    similarCourses: ['B.Plan', 'B.Des Interior Design', 'B.Tech Civil'],
    duration: '5 years',
    eligibility: 'Class 12 PCM with NATA / JEE Paper 2',
    skillsCovered: ['AutoCAD', 'Revit', 'SketchUp', 'Sustainable Design', 'Urban Planning', 'Building Codes'],
    applyLink: search('B.Arch admission India NATA JEE Paper 2'),
    grades: ['class-11', 'class-12', 'graduate'],
  },

  // ============ INTERNSHIPS (8) ============
  {
    id: 'google-step',
    title: 'Google STEP Intern',
    category: 'Internships',
    fieldBadge: 'Software',
    demand: 'Very High',
    description:
      '12-week summer internship for first/second-year undergraduate students interested in CS. Mentorship, real-world project work, and exposure to Google engineering culture.',
    salaryRange: '₹4-6 LPA pro-rated · $8K-$10K/month (US)',
    growthTrend: 'Conversion to full-time offer ~60% for top interns',
    accentColor: 'blue',
    careerOutcomes: ['Software Engineer Intern', 'Return Offer SWE', 'Engineering Resident'],
    salaryProgression: [
      { stage: 'Intern (summer)', salary: '₹1-2L / month' },
      { stage: 'Return Offer L3 (0-2 yrs)', salary: '₹30-50 LPA' },
      { stage: 'L4 Engineer (3-5 yrs)', salary: '₹60-90 LPA' },
      { stage: 'Senior L5+', salary: '₹1-2 Cr' },
    ],
    institutions: ['Google Bangalore', 'Google Hyderabad', 'Google Mountain View', 'Google London'],
    similarCourses: ['Microsoft Engage', 'Meta University', 'AWS Internship'],
    duration: '12 weeks',
    provider: 'Google LLC',
    cost: 'Free to apply',
    eligibility: 'First or second year B.Tech / B.E. / integrated M.Tech; strong CS fundamentals',
    skillsCovered: ['Coding interviews', 'Data Structures', 'Algorithms', 'System Design basics', 'Collaboration', 'Code reviews'],
    applyLink: search('Google STEP Intern application 2025'),
    grades: ['class-12', 'graduate'],
  },
  {
    id: 'microsoft-engage',
    title: 'Microsoft Engage',
    category: 'Internships',
    fieldBadge: 'Software',
    demand: 'Very High',
    description:
      'Mentorship-driven engineering engagement programme for students to build a working prototype over 3-4 weeks. Top performers fast-track to Microsoft internship interviews.',
    salaryRange: 'Stipend ₹30K-50K · Conversion to ₹25-40 LPA',
    growthTrend: 'Top 20% receive pre-placement internship offers',
    accentColor: 'blue',
    careerOutcomes: ['Microsoft SWE Intern', 'Full-time SWE', 'Program Manager'],
    salaryProgression: [
      { stage: 'Engage Participant', salary: 'Certificate + Stipend' },
      { stage: 'Intern (next summer)', salary: '₹30-50K / month' },
      { stage: 'FTE SDE-1', salary: '₹25-40 LPA' },
      { stage: 'Senior SDE', salary: '₹50L-1 Cr' },
    ],
    institutions: ['Microsoft India (Hyderabad / Bangalore)', 'Microsoft Redmond'],
    similarCourses: ['Google STEP', 'Meta University', 'MLH Fellowship'],
    duration: '3-4 weeks',
    provider: 'Microsoft',
    cost: 'Free',
    eligibility: 'Engineering students in 2nd / 3rd year',
    skillsCovered: ['Prototype Design', 'Azure Cloud', 'React / .NET', 'Agile', 'Code Reviews', 'Presentation'],
    applyLink: search('Microsoft Engage programme 2025 application'),
    grades: ['class-12', 'graduate'],
  },
  {
    id: 'meta-university-intern',
    title: 'Meta University Intern',
    category: 'Internships',
    fieldBadge: 'Software',
    demand: 'Very High',
    description:
      'Paid summer internship at Meta for undergraduate students. Work on React, PyTorch, or infrastructure teams. Includes mentorship, intern events, and housing support.',
    salaryRange: '$8K-$11K/month · ₹2-3L/month (India)',
    growthTrend: 'High conversion rate to full-time (70%+)',
    accentColor: 'blue',
    careerOutcomes: ['Software Engineer Intern', 'Return Offer E3', 'Production Engineer'],
    salaryProgression: [
      { stage: 'Intern (summer)', salary: '₹2-3L / month' },
      { stage: 'Return E3 (0-2 yrs)', salary: '₹40-70 LPA' },
      { stage: 'E4 (3-5 yrs)', salary: '₹70L-1.5 Cr' },
      { stage: 'E5 Senior', salary: '₹1-2.5 Cr' },
    ],
    institutions: ['Meta Menlo Park', 'Meta London', 'Meta Bangalore'],
    similarCourses: ['Google STEP', 'Apple Internship', 'Amazon SDE Intern'],
    duration: '12 weeks',
    provider: 'Meta Platforms',
    cost: 'Free to apply',
    eligibility: 'Penultimate year B.Tech / B.E. / M.Tech in CS or related',
    skillsCovered: ['Coding interviews', 'Distributed Systems', 'Hack (PHP)', 'React', 'PyTorch', 'Code Review'],
    applyLink: search('Meta University Intern software engineer 2025'),
    grades: ['class-12', 'graduate'],
  },
  {
    id: 'drdo-internship',
    title: 'DRDO Internship',
    category: 'Internships',
    fieldBadge: 'Defense R&D',
    demand: 'High',
    description:
      'Internship at Defence Research and Development Organisation labs across India — work on missiles, radar, materials, and defense electronics under scientists.',
    salaryRange: '₹8K-25K/month stipend',
    growthTrend: 'Boosts DRDO Scientist-B and PSU recruitment chances',
    accentColor: 'gold',
    careerOutcomes: ['DRDO Scientist', 'Research Associate', 'Defense PSUs (BEL/HAL/BHEL)'],
    salaryProgression: [
      { stage: 'Intern (3-6 months)', salary: '₹8K-25K / month' },
      { stage: 'JRF (1-2 yrs)', salary: '₹37K-42K / month' },
      { stage: 'Scientist B / C', salary: '₹8-15 LPA' },
      { stage: 'Scientist F / G', salary: '₹25-40 LPA' },
    ],
    institutions: ['DRDO Bangalore (ADE)', 'DRDO Hyderabad (RCMA)', 'DRDO Delhi (CAPE', 'DRDO Pune (ARDE)'],
    similarCourses: ['ISRO Internship', 'BARC Training School', 'BEL Internship'],
    duration: '3-6 months',
    provider: 'DRDO (Govt. of India)',
    cost: 'Free',
    eligibility: 'B.E. / B.Tech / M.Sc students with 65%+ aggregate',
    skillsCovered: ['Defense Electronics', 'Radar Systems', 'Materials Science', 'Aerodynamics', 'Embedded C', 'Research Methodology'],
    applyLink: search('DRDO internship application students'),
    grades: ['class-12', 'graduate'],
  },
  {
    id: 'isro-internship',
    title: 'ISRO Internship',
    category: 'Internships',
    fieldBadge: 'Space R&D',
    demand: 'Very High',
    description:
      'Internship at Indian Space Research Organisation centres — work on satellites, launch vehicles, propulsion, and mission control systems. Highly competitive.',
    salaryRange: 'Stipend ₹5K-15K/month',
    growthTrend: 'ISRO recruitment expanding with private space sector',
    accentColor: 'gold',
    careerOutcomes: ['ISRO Scientist/Engineer', 'Satellite Engineer', 'Mission Operations Specialist'],
    salaryProgression: [
      { stage: 'Intern (3-6 months)', salary: '₹5K-15K / month' },
      { stage: 'JRF / RA', salary: '₹37K-58K / month' },
      { stage: 'Scientist/Engineer SC', salary: '₹8-12 LPA' },
      { stage: 'Outstanding Scientist', salary: '₹25-50 LPA' },
    ],
    institutions: ['ISRO HQ Bangalore', 'VSSC Thiruvananthapuram', 'URSC Bangalore', 'LPSC'],
    similarCourses: ['DRDO Internship', 'BARC Training School', 'NASA Internship'],
    duration: '3-6 months',
    provider: 'ISRO (Govt. of India)',
    cost: 'Free',
    eligibility: 'B.E. / B.Tech with 65%+; some slots for M.Sc / MBA',
    skillsCovered: ['Orbital Mechanics', 'Propulsion', 'Satellite Comms', 'Embedded Systems', 'Mission Planning', 'Thermal Engineering'],
    applyLink: search('ISRO internship application student'),
    grades: ['class-12', 'graduate'],
  },
  {
    id: 'goldman-sachs-summer-analyst',
    title: 'Goldman Sachs Summer Analyst',
    category: 'Internships',
    fieldBadge: 'Finance',
    demand: 'Very High',
    description:
      '10-week summer analyst programme across investment banking, securities, and asset management. Includes deal exposure, modeling, and a fast-track to full-time offers.',
    salaryRange: '₹1-2L/month · $1.5K-$3K/week (US)',
    growthTrend: '60-70% intern-to-full-time conversion rate',
    accentColor: 'gold',
    careerOutcomes: ['Investment Banking Analyst', 'Equity Research Analyst', 'Risk Analyst'],
    salaryProgression: [
      { stage: 'Summer Analyst', salary: '₹1-2L / month' },
      { stage: 'FTE Analyst (0-2 yrs)', salary: '₹18-30 LPA' },
      { stage: 'Associate (3-5 yrs)', salary: '₹35-60 LPA' },
      { stage: 'VP', salary: '₹70L-2 Cr' },
    ],
    institutions: ['Goldman Sachs Bangalore', 'Goldman Sachs Mumbai', 'Goldman Sachs NYC', 'Goldman Sachs London'],
    similarCourses: ['JP Morgan Summer Analyst', 'Morgan Stanley Intern', 'Mckinsey Internship'],
    duration: '10 weeks',
    provider: 'Goldman Sachs',
    cost: 'Free to apply',
    eligibility: 'Penultimate year B.E. / B.Tech / B.Com / MBA; strong quant + communication',
    skillsCovered: ['Financial Modeling', 'Excel / VBA', 'DCF Valuation', 'M&A Analysis', 'Bloomberg Terminal', 'Pitch Books'],
    applyLink: search('Goldman Sachs Summer Analyst internship application'),
    grades: ['class-12', 'graduate'],
  },
  {
    id: 'tata-steel-internship',
    title: 'TATA Steel Internship',
    category: 'Internships',
    fieldBadge: 'Manufacturing',
    demand: 'High',
    description:
      'Summer internship at Tata Steel — work on process engineering, supply chain, or sustainability projects at Jamshedpur / Kalinganagar plants.',
    salaryRange: '₹20K-40K/month stipend',
    growthTrend: 'Strong pre-placement offer (PPO) pipeline',
    accentColor: 'gold',
    careerOutcomes: ['Management Trainee', 'Process Engineer', 'Operations Manager'],
    salaryProgression: [
      { stage: 'Intern (2-3 months)', salary: '₹20K-40K / month' },
      { stage: 'GET (0-2 yrs)', salary: '₹8-12 LPA' },
      { stage: 'Manager (3-6 yrs)', salary: '₹15-25 LPA' },
      { stage: 'Senior Manager', salary: '₹30-50 LPA' },
    ],
    institutions: ['Tata Steel Jamshedpur', 'Tata Steel Kalinganagar', 'Tata Steel Long Products'],
    similarCourses: ['Tata Motors Internship', 'JSW Steel Internship', 'L&T Internship'],
    duration: '2-3 months',
    provider: 'Tata Steel',
    cost: 'Free',
    eligibility: 'B.E. / B.Tech pre-final year (Mechanical / Metallurgy / Electrical / Industrial)',
    skillsCovered: ['Process Engineering', 'Lean Manufacturing', 'Six Sigma', 'Supply Chain', 'Quality Control', 'Safety Systems'],
    applyLink: search('Tata Steel summer internship application'),
    grades: ['class-12', 'graduate'],
  },
  {
    id: 'world-bank-internship',
    title: 'World Bank Internship',
    category: 'Internships',
    fieldBadge: 'Public Policy',
    demand: 'Very High',
    description:
      'World Bank Group Internship Programme for graduate students — work on economic research, development projects, and policy analysis across emerging markets.',
    salaryRange: '$3K-$5K/month stipend',
    growthTrend: 'Pipeline to Young Professionals Program (YPP)',
    accentColor: 'blue',
    careerOutcomes: ['Economist', 'Policy Analyst', 'Development Consultant'],
    salaryProgression: [
      { stage: 'Intern (3-6 months)', salary: '$3K-5K / month' },
      { stage: 'Analyst (0-3 yrs)', salary: '$70K-$100K' },
      { stage: 'Senior Analyst', salary: '$110K-$160K' },
      { stage: 'YPP / Sector Lead', salary: '$160K-$250K' },
    ],
    institutions: ['World Bank Washington DC', 'World Bank New Delhi', 'World Bank Nairobi'],
    similarCourses: ['IMF Internship', 'UN Internship', 'ADB Internship'],
    duration: '3-6 months',
    provider: 'World Bank Group',
    cost: 'Free',
    eligibility: 'Graduate (Master\'s) student in economics, public policy, or related fields',
    skillsCovered: ['Econometrics', 'Policy Analysis', 'STATA / R', 'Impact Evaluation', 'Field Research', 'Report Writing'],
    applyLink: search('World Bank Internship Programme application'),
    grades: ['graduate'],
  },

  // ============ GOVT (7) ============
  {
    id: 'pmkvy',
    title: 'PMKVY (Pradhan Mantri Kaushal Vikas Yojana)',
    category: 'Govt',
    fieldBadge: 'Skill India',
    demand: 'High',
    description:
      'Flagship skill-development scheme of the Government of India offering free short-term training in 400+ job roles across sectors. Certification + placement support.',
    salaryRange: 'Free training · ₹8K-25K/month post-certification',
    growthTrend: 'Target: 4 crore youth skilled by 2026',
    accentColor: 'gold',
    careerOutcomes: ['IT Support', 'Retail Associate', 'Hospitality Staff', 'Auto Service Technician', 'BPO Executive'],
    salaryProgression: [
      { stage: 'Trainee', salary: 'Free training + ₹3K stipend' },
      { stage: 'Entry role (0-2 yrs)', salary: '₹8-15K / month' },
      { stage: 'Skilled role', salary: '₹15-25K / month' },
      { stage: 'Supervisor', salary: '₹25-40K / month' },
    ],
    institutions: ['NSDC Training Partners', 'ITI Institutes', 'PMKVY-affiliated centers'],
    similarCourses: ['NDLM Digital Literacy', 'DDU-GKY', 'Apprenticeship ITI'],
    duration: '200-600 hours',
    provider: 'NSDC / Ministry of Skill Development',
    cost: 'Free (govt-funded)',
    eligibility: 'Indian nationals, 15-45 years, Class 10 pass / ITI',
    skillsCovered: ['Sector-specific job role', 'Soft skills', 'Financial & Digital Literacy', 'Entrepreneurship'],
    applyLink: search('PMKVY Pradhan Mantri Kaushal Vikas Yojana register'),
    grades: ['class-10', 'class-11', 'class-12', 'graduate'],
  },
  {
    id: 'nptel',
    title: 'NPTEL Online Certification',
    category: 'Govt',
    fieldBadge: 'Higher Education',
    demand: 'Very High',
    description:
      'Free online courses from IITs and IISc, proctored certification exams at nominal fees. 600+ courses across engineering, sciences, humanities, and management.',
    salaryRange: 'Courses free · ₹1,000 certification exam',
    growthTrend: '40+ lakh enrolments per semester',
    accentColor: 'blue',
    careerOutcomes: ['Resume Boost for Higher Studies', 'Job Application Edge', 'Faculty Lateral Entry'],
    salaryProgression: [
      { stage: 'Cert holder', salary: 'Resume differentiator' },
      { stage: 'Entry (0-2 yrs)', salary: '₹5-12 LPA' },
      { stage: 'Mid (3-6 yrs)', salary: '₹12-25 LPA' },
      { stage: 'Senior', salary: '₹25-50 LPA' },
    ],
    institutions: ['IIT Madras', 'IIT Bombay', 'IIT Delhi', 'IISc Bangalore', 'IIT Kanpur'],
    similarCourses: ['SWAYAM', 'Coursera for Campus', 'C-DAC Courses'],
    duration: '4-12 weeks / course',
    provider: 'NPTEL (IITs + IISc)',
    cost: '₹1,000 per certification exam',
    eligibility: 'Open to all — students, working professionals, faculty',
    skillsCovered: ['Engineering subjects', 'Programming (Python, Java, R)', 'Data Science', 'Management', 'Mathematics'],
    applyLink: search('NPTEL online certification courses'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'swayam',
    title: 'SWAYAM Courses',
    category: 'Govt',
    fieldBadge: 'MOOC',
    demand: 'Very High',
    description:
      'Free online courses from India\'s best teachers covering school (Class 9-12), undergraduate, and postgraduate subjects. Includes video lectures, weekly assignments, and proctored exams.',
    salaryRange: 'Courses free · ₹1,000 certification',
    growthTrend: '2 crore+ learners enrolled',
    accentColor: 'blue',
    careerOutcomes: ['Academic Mastery', 'Credit Transfer', 'Career Switch Foundation'],
    salaryProgression: [
      { stage: 'Cert holder', salary: 'Skill validation' },
      { stage: 'Entry (0-2 yrs)', salary: '₹4-10 LPA' },
      { stage: 'Mid (3-6 yrs)', salary: '₹10-22 LPA' },
      { stage: 'Senior', salary: '₹22-45 LPA' },
    ],
    institutions: ['IITs', 'IIMs', 'NCERT', 'IGNOU', 'CUs'],
    similarCourses: ['NPTEL', 'Coursera', 'edX'],
    duration: '8-16 weeks',
    provider: 'Ministry of Education (India)',
    cost: 'Free; ₹1,000 certification',
    eligibility: 'Open to all Indian nationals; some courses need Class 12',
    skillsCovered: ['Subject mastery', 'Assignments', 'Proctored exams', 'Credit transfer'],
    applyLink: search('SWAYAM free online courses India'),
    grades: ['class-9', 'class-10', 'class-11', 'class-12', 'graduate'],
  },
  {
    id: 'aicte-internship',
    title: 'AICTE Internship Portal',
    category: 'Govt',
    fieldBadge: 'Internship',
    demand: 'Very High',
    description:
      'Government-mandated portal connecting students with industry, research, and govt internships. Mandatory for engineering students; stipend-bearing opportunities across India.',
    salaryRange: '₹5K-25K/month stipend',
    growthTrend: '5L+ internships listed annually',
    accentColor: 'gold',
    careerOutcomes: ['Industry Intern', 'Research Intern', 'Govt Intern', 'PPO Convert'],
    salaryProgression: [
      { stage: 'Intern (3-6 months)', salary: '₹5K-25K / month' },
      { stage: 'Entry (0-2 yrs)', salary: '₹5-12 LPA' },
      { stage: 'Mid (3-6 yrs)', salary: '₹12-25 LPA' },
      { stage: 'Senior', salary: '₹25-50 LPA' },
    ],
    institutions: ['TCS', 'Infosys', 'Wipro', 'L&T', 'BHEL', 'BEL', 'DRDO', 'ISRO'],
    similarCourses: ['PMKVY', 'DRDO Internship', 'ISRO Internship'],
    duration: '3-6 months',
    provider: 'AICTE / Ministry of Education',
    cost: 'Free',
    eligibility: 'AICTE-approved institute students; engineering / management / pharmacy',
    skillsCovered: ['Industry-ready skills', 'Project work', 'Soft skills', 'Professional etiquette'],
    applyLink: search('AICTE internship portal register student'),
    grades: ['class-12', 'graduate'],
  },
  {
    id: 'ndl-india',
    title: 'National Digital Library (NDLI)',
    category: 'Govt',
    fieldBadge: 'Library',
    demand: 'High',
    description:
      'Free digital library by IIT Kharagpur with 60M+ resources — textbooks, journals, video lectures, and curated subject collections across all disciplines.',
    salaryRange: 'Free · Supports academic excellence',
    growthTrend: '60M+ items indexed; used by 50L+ learners',
    accentColor: 'blue',
    careerOutcomes: ['Self-learners', 'Exam prep boost', 'Research foundation'],
    salaryProgression: [
      { stage: 'Learner', salary: 'Skill enhancement' },
      { stage: 'Entry (0-2 yrs)', salary: '₹4-10 LPA' },
      { stage: 'Mid (3-6 yrs)', salary: '₹10-22 LPA' },
      { stage: 'Senior', salary: '₹22-45 LPA' },
    ],
    institutions: ['IIT Kharagpur', 'IISc', 'CSIR Labs', 'NCERT', 'IGNOU'],
    similarCourses: ['NPTEL', 'SWAYAM', 'e-PG Pathshala'],
    duration: 'Self-paced',
    provider: 'Ministry of Education',
    cost: 'Free',
    eligibility: 'Open to all — students, faculty, researchers',
    skillsCovered: ['Research skills', 'Subject mastery', 'Reference management'],
    applyLink: search('National Digital Library India NDLI'),
    grades: ['class-8', 'class-9', 'class-10', 'class-11', 'class-12', 'graduate'],
  },
  {
    id: 'ndlm',
    title: 'NDLM / PMGDISHA Digital Literacy',
    category: 'Govt',
    fieldBadge: 'Digital Literacy',
    demand: 'Medium',
    description:
      'Government scheme certifying basic digital literacy — operating smartphones, using online govt services, digital payments, and internet safety. Aimed at rural + semi-urban India.',
    salaryRange: 'Free · enables entry-level digital jobs',
    growthTrend: '6 crore households to be covered under PMGDISHA',
    accentColor: 'gold',
    careerOutcomes: ['Data Entry Operator', 'CSC Operator', 'Digital Services Agent', 'BPO Executive'],
    salaryProgression: [
      { stage: 'Trainee', salary: 'Free training' },
      { stage: 'Entry (0-2 yrs)', salary: '₹8-15K / month' },
      { stage: 'Skilled role', salary: '₹15-25K / month' },
      { stage: 'Supervisor / Owner', salary: '₹25-50K / month' },
    ],
    institutions: ['Common Service Centers (CSC)', 'VLE-operated centres'],
    similarCourses: ['PMKVY IT-ITeS', 'DDU-GKY', 'RKCL RS-CFA'],
    duration: '20-40 hours',
    provider: 'MeitY / CSC e-Governance',
    cost: 'Free',
    eligibility: 'Indian nationals 14+ years; no prior digital skills needed',
    skillsCovered: ['Operating devices', 'Internet basics', 'Digital payments', 'Govt e-services', 'Email & social media safety'],
    applyLink: search('NDLM PMGDISHA digital literacy certification register'),
    grades: ['class-8', 'class-9', 'class-10', 'class-11', 'class-12'],
  },
  {
    id: 'ignou-distance',
    title: 'IGNOU Distance Education Programmes',
    category: 'Govt',
    fieldBadge: 'Distance Learning',
    demand: 'High',
    description:
      'World\'s largest open university — 200+ programmes at certificate, diploma, degree, and postgraduate levels. Flexible study for working professionals and rural learners.',
    salaryRange: 'Fees ₹2K-25K per programme',
    growthTrend: '4 million+ active learners',
    accentColor: 'gold',
    careerOutcomes: ['Graduate degrees', 'Career-switch pathway', 'Skill certifications'],
    salaryProgression: [
      { stage: 'Student', salary: 'Skill / degree gain' },
      { stage: 'Entry (0-2 yrs)', salary: '₹3-8 LPA' },
      { stage: 'Mid (3-6 yrs)', salary: '₹8-18 LPA' },
      { stage: 'Senior', salary: '₹18-35 LPA' },
    ],
    institutions: ['IGNOU HQ Delhi', '56 Regional Centres', '2,000+ Study Centres'],
    similarCourses: ['SWAYAM Degree', 'NSOU', 'Annamalai Distance'],
    duration: '6 months - 3 years',
    provider: 'IGNOU',
    cost: '₹2,000 - ₹25,000',
    eligibility: 'Varies by programme; most need Class 10 / 12 pass',
    skillsCovered: ['Subject mastery', 'Self-discipline', 'Assignment writing', 'Term-end exams'],
    applyLink: search('IGNOU distance education admission online'),
    grades: ['class-10', 'class-11', 'class-12', 'graduate'],
  },

  // ============ SHORT (6) ============
  {
    id: 'coursera-ml',
    title: 'Coursera Machine Learning Specialization',
    category: 'Short',
    fieldBadge: 'AI/ML',
    demand: 'Very High',
    description:
      '3-course specialization by Andrew Ng (Stanford / DeepLearning.AI) covering supervised learning, neural networks, and recommender systems. Hands-on Python + NumPy labs.',
    salaryRange: '₹3K-5K total · boosts salary by 15-25%',
    growthTrend: '#1 most-enrolled ML specialization globally',
    accentColor: 'blue',
    careerOutcomes: ['ML Engineer', 'Data Scientist', 'AI Researcher', 'ML Intern'],
    salaryProgression: [
      { stage: 'Pre-cert', salary: '₹3-6 LPA' },
      { stage: 'Post-cert (0-2 yrs)', salary: '₹6-12 LPA' },
      { stage: 'Mid (3-5 yrs)', salary: '₹14-30 LPA' },
      { stage: 'Senior', salary: '₹30-70 LPA' },
    ],
    institutions: ['Coursera', 'DeepLearning.AI', 'Stanford University'],
    similarCourses: ['Deep Learning Specialization', 'AWS ML Specialty', 'TensorFlow Certificate'],
    duration: '2-3 months',
    provider: 'Coursera / DeepLearning.AI',
    cost: '₹3,000-5,000',
    eligibility: 'Basic Python + high-school math',
    skillsCovered: ['Linear / Logistic Regression', 'Neural Networks', 'Gradient Descent', 'NumPy', 'Scikit-learn', ' Recommender Systems'],
    applyLink: search('Coursera Machine Learning Specialization Andrew Ng'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'google-data-analytics',
    title: 'Google Data Analytics Professional Certificate',
    category: 'Short',
    fieldBadge: 'Data',
    demand: 'Very High',
    description:
      '8-course certificate by Google teaching data cleaning, analysis, visualization, R, and Tableau. Includes case study project + job-placement resources.',
    salaryRange: '₹8K-12K total · entry analyst ₹4-8 LPA',
    growthTrend: 'Direct hiring consortium with 150+ employers',
    accentColor: 'blue',
    careerOutcomes: ['Junior Data Analyst', 'Business Analyst', 'Operations Analyst'],
    salaryProgression: [
      { stage: 'Pre-cert', salary: '₹2-4 LPA' },
      { stage: 'Post-cert (0-2 yrs)', salary: '₹4-8 LPA' },
      { stage: 'Mid (3-5 yrs)', salary: '₹10-20 LPA' },
      { stage: 'Senior Analyst', salary: '₹20-40 LPA' },
    ],
    institutions: ['Coursera', 'Google', 'Hiring consortium (TCS, Wipro, Infosys)'],
    similarCourses: ['IBM Data Science Pro', 'Microsoft Power BI DA', 'Tableau Specialist'],
    duration: '6 months @ 10 hrs/week',
    provider: 'Coursera / Google',
    cost: '₹8,000-12,000',
    eligibility: 'No prior experience needed',
    skillsCovered: ['Spreadsheet (Excel/Sheets)', 'SQL', 'R Programming', 'Tableau', 'Data Visualization', 'Storytelling with data'],
    applyLink: search('Google Data Analytics Professional Certificate Coursera'),
    grades: ['class-10', 'class-11', 'class-12', 'graduate'],
  },
  {
    id: 'aws-cloud-practitioner',
    title: 'AWS Certified Cloud Practitioner',
    category: 'Short',
    fieldBadge: 'Cloud',
    demand: 'Very High',
    description:
      'Foundational AWS certification validating cloud concepts, AWS core services, security, billing, and pricing. Globally recognized, 90-min proctored exam.',
    salaryRange: '₹2K-4K exam · salary bump 10-20%',
    growthTrend: 'AWS = 32% cloud market share',
    accentColor: 'blue',
    careerOutcomes: ['Cloud Support Associate', 'Solutions Architect (entry)', 'DevOps Intern'],
    salaryProgression: [
      { stage: 'Pre-cert', salary: '₹3-6 LPA' },
      { stage: 'Post-cert (0-2 yrs)', salary: '₹6-12 LPA' },
      { stage: 'Mid (3-5 yrs)', salary: '₹12-25 LPA' },
      { stage: 'Senior Cloud Architect', salary: '₹30-60 LPA' },
    ],
    institutions: ['Amazon Web Services', 'AWS Training Partners'],
    similarCourses: ['Azure Fundamentals AZ-900', 'GCP Cloud Digital Leader', 'AWS Solutions Architect'],
    duration: '1-2 months prep',
    provider: 'Amazon Web Services',
    cost: '₹2,200-4,000',
    eligibility: 'Open to all; recommended 6 months AWS exposure',
    skillsCovered: ['Cloud Concepts', 'AWS Core Services', 'Security & Compliance', 'Billing & Pricing', 'AWS Console'],
    applyLink: search('AWS Certified Cloud Practitioner exam'),
    grades: ['class-11', 'class-12', 'graduate'],
  },
  {
    id: 'ibm-data-science',
    title: 'IBM Data Science Professional Certificate',
    category: 'Short',
    fieldBadge: 'Data Science',
    demand: 'Very High',
    description:
      '10-course certificate covering Python, SQL, data viz, ML, and capstone project with IBM Watson Studio. Includes IBM digital badge.',
    salaryRange: '₹8K-12K total · ₹6-15 LPA post-cert',
    growthTrend: 'Industry-recognised IBM badge on Credly',
    accentColor: 'blue',
    careerOutcomes: ['Data Scientist', 'Data Analyst', 'ML Engineer (entry)'],
    salaryProgression: [
      { stage: 'Pre-cert', salary: '₹3-5 LPA' },
      { stage: 'Post-cert (0-2 yrs)', salary: '₹6-12 LPA' },
      { stage: 'Mid (3-5 yrs)', salary: '₹14-28 LPA' },
      { stage: 'Senior Data Scientist', salary: '₹30-60 LPA' },
    ],
    institutions: ['Coursera', 'IBM', 'IBM Watson Studio'],
    similarCourses: ['Google Data Analytics', 'Coursera ML Specialization', 'Microsoft Data Science'],
    duration: '5-8 months @ 4 hrs/week',
    provider: 'Coursera / IBM',
    cost: '₹8,000-12,000',
    eligibility: 'No prior experience needed',
    skillsCovered: ['Python', 'SQL', 'Pandas', 'Matplotlib', 'Scikit-learn', 'Jupyter Notebooks', 'IBM Watson'],
    applyLink: search('IBM Data Science Professional Certificate Coursera'),
    grades: ['class-10', 'class-11', 'class-12', 'graduate'],
  },
  {
    id: 'udemy-python-bootcamp',
    title: '100 Days of Code: The Complete Python Pro Bootcamp (Udemy)',
    category: 'Short',
    fieldBadge: 'Programming',
    demand: 'Very High',
    description:
      'Bestselling Udemy bootcamp by Angela Yu — 100 daily projects covering Python fundamentals to web scraping, automation, Flask, and data science.',
    salaryRange: '₹500-1,500 · portfolio-ready projects',
    growthTrend: 'Top 5 Python course on Udemy',
    accentColor: 'gold',
    careerOutcomes: ['Python Developer', 'Automation Engineer (entry)', 'Web Developer'],
    salaryProgression: [
      { stage: 'Pre-course', salary: '₹2-4 LPA' },
      { stage: 'Post-course (0-2 yrs)', salary: '₹5-10 LPA' },
      { stage: 'Mid (3-5 yrs)', salary: '₹12-22 LPA' },
      { stage: 'Senior', salary: '₹25-50 LPA' },
    ],
    institutions: ['Udemy', 'App Brewery (Angela Yu)'],
    similarCourses: ['Python for Everybody (Coursera)', 'Automate the Boring Stuff', 'Real Python'],
    duration: '100 days (50-100 hrs total)',
    provider: 'Udemy',
    cost: '₹500-1,500',
    eligibility: 'No prior coding experience needed',
    skillsCovered: ['Python fundamentals', 'OOP', 'Web scraping', 'Flask', 'APIs', 'Automation', 'Data Science basics'],
    applyLink: search('100 Days of Code Python Pro Bootcamp Udemy Angela Yu'),
    grades: ['class-8', 'class-9', 'class-10', 'class-11', 'class-12', 'graduate'],
  },
  {
    id: 'edx-cs50',
    title: 'CS50x: Introduction to Computer Science (Harvard / edX)',
    category: 'Short',
    fieldBadge: 'CS Fundamentals',
    demand: 'Very High',
    description:
      'Harvard\'s legendary CS50 course — free on edX. Covers C, Python, SQL, JavaScript, and the art of computational thinking. 11 weeks, project-based.',
    salaryRange: 'Free · ₹2K-3K verified certificate',
    growthTrend: 'Most-enrolled course in Harvard history',
    accentColor: 'blue',
    careerOutcomes: ['CS Foundation for Higher Studies', 'Entry Developer Roles', 'Tech Interviews Prep'],
    salaryProgression: [
      { stage: 'Pre-course', salary: '₹2-4 LPA' },
      { stage: 'Post-course (0-2 yrs)', salary: '₹5-10 LPA' },
      { stage: 'Mid (3-5 yrs)', salary: '₹12-25 LPA' },
      { stage: 'Senior Engineer', salary: '₹25-55 LPA' },
    ],
    institutions: ['Harvard University', 'edX'],
    similarCourses: ['MIT 6.00.1x', 'CS50 Web', 'CS50 AI'],
    duration: '11 weeks @ 10-20 hrs/week',
    provider: 'Harvard / edX',
    cost: 'Free; ₹2,000-3,000 certificate',
    eligibility: 'Open to all; no prior CS experience',
    skillsCovered: ['C programming', 'Python', 'SQL', 'JavaScript', 'Algorithms', 'Data Structures', 'Computational Thinking'],
    applyLink: search('CS50 Harvard edX introduction computer science'),
    grades: ['class-9', 'class-10', 'class-11', 'class-12', 'graduate'],
  },
];

/**
 * Returns the count of items per category.
 */
export function discoverCounts(): Record<DiscoverCategory, number> {
  const counts: Record<DiscoverCategory, number> = { Courses: 0, Internships: 0, Govt: 0, Short: 0 };
  for (const item of DISCOVER_ITEMS) counts[item.category] += 1;
  return counts;
}

/**
 * Returns all distinct field badges across items (useful for search filters).
 */
export function discoverFields(): string[] {
  return Array.from(new Set(DISCOVER_ITEMS.map((i) => i.fieldBadge))).sort();
}
