import type { University } from './types';

// Universities across 10 countries: USA, Canada, UK, Germany, Australia,
// New Zealand, Ireland, Singapore, Netherlands, Sweden

export const UNIVERSITIES: University[] = [
  // ---- USA (5) ----
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology (MIT)',
    country: 'USA',
    ranking: 1,
    acceptanceRate: '4.1%',
    tuitionFees: '$60,946 / year (undergraduate)',
    scholarships: [
      'MIT Need-Based Aid',
      'MIT Presidential Fellowship',
      'Stanley R. Klindt Endowed Scholarship',
    ],
    livingCost: '$24,000-$28,000 / year',
    accommodation: 'On-campus housing guaranteed for first year; $12,000-$18,000 / year.',
    visaDetails:
      'F-1 student visa required. I-20 issued after admission and proof of funds. Must show ~$85,000 in bank statements. OPT allows 12 months of post-study work (36 months for STEM).',
    employmentRate: '95% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Electrical Engineering', 'Mechanical Engineering', 'Physics', 'AI/ML'],
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    country: 'USA',
    ranking: 3,
    acceptanceRate: '3.7%',
    tuitionFees: '$65,127 / year (undergraduate)',
    scholarships: [
      'Stanford Need-Based Aid',
      'Knight-Hennessy Scholars',
      'Stanford Graduate Fellowships',
    ],
    livingCost: '$26,000-$32,000 / year',
    accommodation: 'On-campus housing available; $13,000-$17,000 / year.',
    visaDetails:
      'F-1 visa. I-20 requires proof of ~$90,000 funds. Stanford offers extensive financial aid for international students. STEM OPT extends work authorization to 36 months.',
    employmentRate: '94% within 6 months of graduation',
    popularCourses: ['Computer Science', 'MBA', 'Design (d.school)', 'Engineering', 'Bioengineering'],
  },
  {
    id: 'harvard',
    name: 'Harvard University',
    country: 'USA',
    ranking: 4,
    acceptanceRate: '3.4%',
    tuitionFees: '$59,320 / year (undergraduate)',
    scholarships: [
      'Harvard Financial Aid Initiative',
      'Harvard MBA Forward Fellowship',
      'Boustany MBA Harvard Scholarship',
    ],
    livingCost: '$22,000-$28,000 / year',
    accommodation: 'House system for undergrads; $12,000-$16,000 / year.',
    visaDetails:
      'F-1 visa required. Harvard sponsors I-20 with ~$85,000 cost-of-attendance. Need-blind admission for international students (limited). OPT and STEM OPT available post-graduation.',
    employmentRate: '93% within 6 months of graduation',
    popularCourses: ['Law (JD)', 'MBA', 'Computer Science', 'Public Policy', 'Medicine'],
  },
  {
    id: 'caltech',
    name: 'California Institute of Technology (Caltech)',
    country: 'USA',
    ranking: 6,
    acceptanceRate: '2.7%',
    tuitionFees: '$63,402 / year (undergraduate)',
    scholarships: ['Caltech Need-Based Aid', 'Caltech Graduate Fellowships'],
    livingCost: '$24,000-$28,000 / year',
    accommodation: 'On-campus housing guaranteed; $11,000-$15,000 / year.',
    visaDetails:
      'F-1 visa with I-20 requiring ~$85,000 proof of funds. Caltech meets 100% of demonstrated financial need for international undergrads. STEM OPT eligible.',
    employmentRate: '92% within 6 months of graduation',
    popularCourses: ['Physics', 'Computer Science', 'Electrical Engineering', 'Astronomy', 'Chemistry'],
  },
  {
    id: 'cmu',
    name: 'Carnegie Mellon University',
    country: 'USA',
    ranking: 24,
    acceptanceRate: '11.3%',
    tuitionFees: '$64,596 / year (undergraduate)',
    scholarships: ['CMU Need-Based Aid', 'Carnegie Scholarship', 'MSCS Graduate Fellowships'],
    livingCost: '$22,000-$26,000 / year',
    accommodation: 'On-campus housing for first year; $10,000-$14,000 / year.',
    visaDetails:
      'F-1 visa required. I-20 needs ~$84,000 proof of funds. Strong STEM OPT (36 months) for CS, AI, robotics graduates.',
    employmentRate: '95% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Artificial Intelligence', 'Robotics', 'Information Systems', 'Engineering'],
  },
  // ---- Canada (3) ----
  {
    id: 'utoronto',
    name: 'University of Toronto',
    country: 'Canada',
    ranking: 21,
    acceptanceRate: '43%',
    tuitionFees: 'CAD 60,510 / year (international undergraduate)',
    scholarships: ['Lester B. Pearson International Scholarship', 'U of T Scholars Award', 'Vanier CGS (graduate)'],
    livingCost: 'CAD 15,000-$20,000 / year',
    accommodation: 'Residence guaranteed for first-year; CAD 10,000-$15,000 / year.',
    visaDetails:
      'Study Permit required. LOA from U of T needed. PGWP allows up to 3 years post-study work. Proof of ~CAD 30,000 funds required.',
    employmentRate: '93% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Engineering', 'Rotman MBA', 'Medicine', 'Data Science'],
  },
  {
    id: 'ubc',
    name: 'University of British Columbia',
    country: 'Canada',
    ranking: 34,
    acceptanceRate: '52%',
    tuitionFees: 'CAD 47,000-$58,000 / year (international undergraduate)',
    scholarships: ['Karen McKellin International Leader of Tomorrow', 'UBC International Major Entrance Scholarship', 'Vanier CGS'],
    livingCost: 'CAD 16,000-$20,000 / year',
    accommodation: 'On-campus housing for first-year; CAD 9,000-$14,000 / year.',
    visaDetails:
      'Study Permit required. PGWP eligible. Vancouver is a tech hub with strong post-study hiring. Proof of CAD 25,000+ funds.',
    employmentRate: '92% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Forestry', 'Sauder MBA', 'Engineering', 'Biotechnology'],
  },
  {
    id: 'mcgill',
    name: 'McGill University',
    country: 'Canada',
    ranking: 30,
    acceptanceRate: '46%',
    tuitionFees: 'CAD 52,000-$60,000 / year (international undergraduate)',
    scholarships: ['McGill Entrance Bursary', 'Major Entrance Scholarship', 'Vanier CGS'],
    livingCost: 'CAD 14,000-$18,000 / year',
    accommodation: 'Residences available; CAD 9,000-$13,000 / year.',
    visaDetails:
      'Study Permit required, Quebec Acceptance Certificate (CAQ) also needed. PGWP eligible. Montreal is affordable with strong AI ecosystem.',
    employmentRate: '91% within 6 months of graduation',
    popularCourses: ['Medicine', 'Law', 'Computer Science', 'Engineering', 'Management'],
  },
  // ---- UK (4) ----
  {
    id: 'oxford',
    name: 'University of Oxford',
    country: 'UK',
    ranking: 1,
    acceptanceRate: '17.5%',
    tuitionFees: '£33,050-£48,620 / year (international undergraduate)',
    scholarships: ['Rhodes Scholarship', 'Clarendon Fund', 'Reach Oxford Scholarship'],
    livingCost: '£15,000-£18,000 / year',
    accommodation: 'College accommodation guaranteed for full course; £7,000-£12,000 / year.',
    visaDetails:
      'Student Visa (Tier 4) required. CAS issued after offer acceptance and deposit. Graduate Route allows 2 years post-study work (3 for PhD).',
    employmentRate: '95% within 6 months of graduation',
    popularCourses: ['PPE', 'Computer Science', 'Medicine', 'Law (Jurisprudence)', 'MBA'],
  },
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    country: 'UK',
    ranking: 2,
    acceptanceRate: '21%',
    tuitionFees: '£30,339-£63,990 / year (international undergraduate)',
    scholarships: ['Gates Cambridge Scholarship', 'Cambridge Trust Scholarships', 'Churchill Scholarship'],
    livingCost: '£14,000-£17,000 / year',
    accommodation: 'College accommodation guaranteed; £7,000-£11,000 / year.',
    visaDetails:
      'Student Visa (Tier 4) required. CAS issued post-offer. Graduate Route allows 2 years post-study work (3 for PhD).',
    employmentRate: '95% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Engineering', 'Natural Sciences', 'Mathematics', 'Medicine'],
  },
  {
    id: 'imperial',
    name: 'Imperial College London',
    country: 'UK',
    ranking: 6,
    acceptanceRate: '14.3%',
    tuitionFees: '£37,900-£44,300 / year (international undergraduate)',
    scholarships: ['Imperial President’s Scholarship', 'Imperial Future Leaders Scholarship', 'Chevening Scholarship'],
    livingCost: '£18,000-£22,000 / year (London)',
    accommodation: 'Limited college housing; £9,000-£14,000 / year.',
    visaDetails:
      'Student Visa required. CAS issued post-offer. Graduate Route permits 2 years post-study work. London-based — high living costs.',
    employmentRate: '94% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Engineering', 'Business (Imperial MBA)', 'Medicine', 'Physics'],
  },
  {
    id: 'ucl',
    name: 'University College London (UCL)',
    country: 'UK',
    ranking: 22,
    acceptanceRate: '32%',
    tuitionFees: '£29,500-£40,000 / year (international undergraduate)',
    scholarships: ['UCL Global Undergraduate Scholarship', 'UCL India Excellence Scholarship', 'Chevening Scholarship'],
    livingCost: '£17,000-£21,000 / year (London)',
    accommodation: 'UCL accommodation for first-year; £9,000-£13,000 / year.',
    visaDetails:
      'Student Visa required. CAS issued post-offer. Graduate Route gives 2 years post-study work authorization.',
    employmentRate: '92% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Architecture', 'Economics', 'Law', 'Neuroscience'],
  },
  // ---- Germany (3) ----
  {
    id: 'tum',
    name: 'Technical University of Munich (TUM)',
    country: 'Germany',
    ranking: 28,
    acceptanceRate: '8-12% (varies by programme)',
    tuitionFees: '€0-€3,000 / semester (Bavaria; international students pay modest fees from 2024)',
    scholarships: ['DAAD Scholarship', 'Deutschlandstipendium', 'TUM Graduate School Funding'],
    livingCost: '€12,000-€14,000 / year (Munich)',
    accommodation: 'Studentenwerk residence €400-€700/month; private €700-€1,000/month.',
    visaDetails:
      'Student Visa required. Blocked account with €11,208/year required. 18-month post-study work visa available. APS certificate mandatory for Indian applicants.',
    employmentRate: '93% within 6 months of graduation',
    popularCourses: ['Computer Science (Informatics)', 'Mechanical Engineering', 'Aerospace', 'Data Engineering', 'Robotics'],
  },
  {
    id: 'eth-zurich',
    name: 'ETH Zurich',
    country: 'Germany',
    ranking: 7,
    acceptanceRate: '27%',
    tuitionFees: 'CHF 1,460 / semester (low tuition — Swiss public model)',
    scholarships: ['ETH Excellence Scholarship', 'ESOP Scholarship', 'Swiss Government Excellence Scholarship'],
    livingCost: 'CHF 21,000-CHF 25,000 / year (Zurich)',
    accommodation: 'Limited student housing; CHF 800-CHF 1,500/month.',
    visaDetails:
      'Swiss Student Visa required. Note: ETH is in Switzerland (German-speaking region) — listed here as German-language. B-permit allows part-time work. Post-study job search visa available.',
    employmentRate: '95% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Mechanical Engineering', 'Architecture', 'Physics', 'Data Science'],
  },
  {
    id: 'rwth-aachen',
    name: 'RWTH Aachen University',
    country: 'Germany',
    ranking: 99,
    acceptanceRate: '20-30%',
    tuitionFees: '€0-€1,500 / semester (NRW; small semester fee)',
    scholarships: ['DAAD Scholarship', 'Deutschlandstipendium', 'RWTH Graduate Funding'],
    livingCost: '€11,000-€13,000 / year (Aachen)',
    accommodation: 'Student residences €400-€600/month; private €600-€900/month.',
    visaDetails:
      'Student Visa required. Blocked account €11,208/year mandatory. 18-month post-study work visa. APS certificate needed for Indian applicants.',
    employmentRate: '90% within 6 months of graduation',
    popularCourses: ['Mechanical Engineering', 'Computer Science', 'Automotive Engineering', 'Materials Science', 'Robotics'],
  },
  // ---- Australia (3) ----
  {
    id: 'unimelb',
    name: 'University of Melbourne',
    country: 'Australia',
    ranking: 13,
    acceptanceRate: '70-80% (international, varies by course)',
    tuitionFees: 'AUD 45,000-AUD 55,000 / year (international undergraduate)',
    scholarships: ['Melbourne Graduate Research Scholarship', 'Melbourne International Undergraduate Scholarship', 'Australia Awards'],
    livingCost: 'AUD 22,000-AUD 27,000 / year',
    accommodation: 'Residential colleges and university housing AUD 14,000-AUD 22,000/year.',
    visaDetails:
      'Subclass 500 Student Visa required. GTE (Genuine Temporary Entrant) statement needed. Temporary Graduate Visa (485) allows 2-4 years post-study work.',
    employmentRate: '91% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Engineering', 'Melbourne MBA', 'Medicine', 'Architecture'],
  },
  {
    id: 'anu',
    name: 'Australian National University (ANU)',
    country: 'Australia',
    ranking: 30,
    acceptanceRate: '35-50%',
    tuitionFees: 'AUD 46,000-AUD 52,000 / year (international undergraduate)',
    scholarships: ['ANU Chancellor’s International Scholarship', 'ANU Tuition Scholarship', 'Australia Awards'],
    livingCost: 'AUD 20,000-AUD 24,000 / year (Canberra)',
    accommodation: 'On-campus residences AUD 13,000-AUD 18,000/year.',
    visaDetails:
      'Subclass 500 Student Visa. Subclass 485 Temporary Graduate Visa for post-study work (2-4 years). Canberra offers PR-friendly pathways.',
    employmentRate: '90% within 6 months of graduation',
    popularCourses: ['International Relations', 'Computer Science', 'Astrophysics', 'Public Policy', 'Engineering'],
  },
  {
    id: 'unsw',
    name: 'University of New South Wales (UNSW Sydney)',
    country: 'Australia',
    ranking: 19,
    acceptanceRate: '60-70%',
    tuitionFees: 'AUD 47,000-AUD 56,000 / year (international undergraduate)',
    scholarships: ['UNSW International Scholarship', 'Future of Change Scholarship', 'Australia Awards'],
    livingCost: 'AUD 22,000-AUD 28,000 / year (Sydney)',
    accommodation: 'On-campus colleges and apartments AUD 14,000-AUD 22,000/year.',
    visaDetails:
      'Subclass 500 Student Visa. Subclass 485 Temporary Graduate Visa for 2-4 years post-study work. Sydney has strong tech & finance hiring.',
    employmentRate: '92% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Engineering', 'Architecture', 'MBA', 'Renewable Energy'],
  },
  // ---- New Zealand (2) ----
  {
    id: 'auckland',
    name: 'University of Auckland',
    country: 'New Zealand',
    ranking: 65,
    acceptanceRate: '50-60%',
    tuitionFees: 'NZD 38,000-NZD 50,000 / year (international undergraduate)',
    scholarships: ['University of Auckland International Student Excellence Scholarship', 'NZ Excellence Awards', 'Manaaki New Zealand Scholarship'],
    livingCost: 'NZD 20,000-NZD 24,000 / year (Auckland)',
    accommodation: 'University halls NZD 14,000-NZD 19,000/year; private NZD 12,000-NZD 18,000/year.',
    visaDetails:
      'Student Visa required. Post-Study Work Visa allows 3 years post-study work. Pathway to PR via Skilled Migrant Category.',
    employmentRate: '89% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Engineering', 'Medicine', 'Business', 'Marine Science'],
  },
  {
    id: 'otago',
    name: 'University of Otago',
    country: 'New Zealand',
    ranking: 217,
    acceptanceRate: '55-65%',
    tuitionFees: 'NZD 36,000-NZD 48,000 / year (international undergraduate)',
    scholarships: ['University of Otago International Excellence Scholarship', 'NZ Excellence Awards', 'Otago Postgraduate Scholarship'],
    livingCost: 'NZD 18,000-NZD 22,000 / year (Dunedin)',
    accommodation: 'Residential colleges NZD 14,000-NZD 18,000/year.',
    visaDetails:
      'Student Visa required. Post-Study Work Visa allows 3 years. Dunedin is a student city with affordable living. PR pathways via skilled migration.',
    employmentRate: '88% within 6 months of graduation',
    popularCourses: ['Medicine', 'Dentistry', 'Health Sciences', 'Sciences', 'Humanities'],
  },
  // ---- Ireland (2) ----
  {
    id: 'tcd',
    name: 'Trinity College Dublin (TCD)',
    country: 'Ireland',
    ranking: 87,
    acceptanceRate: '33%',
    tuitionFees: '€22,000-€30,000 / year (international undergraduate)',
    scholarships: ['Trinity Global Excellence Scholarship', 'Government of Ireland International Education Scholarship', 'Trinity Foundation Scholarship'],
    livingCost: '€14,000-€18,000 / year (Dublin)',
    accommodation: 'Trinity Halls for first year; €8,000-€14,000/year.',
    visaDetails:
      'Long Stay D visa required. IRP registration mandatory. Third Level Graduate Scheme allows 2 years post-study work. Ireland is EU headquarters for Google, Meta, Apple.',
    employmentRate: '93% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Business', 'Law', 'Engineering', 'Medicine'],
  },
  {
    id: 'ucd',
    name: 'University College Dublin (UCD)',
    country: 'Ireland',
    ranking: 126,
    acceptanceRate: '40-50%',
    tuitionFees: '€22,000-€28,000 / year (international undergraduate)',
    scholarships: ['UCD Global Excellence Scholarship', 'Government of Ireland Scholarship', 'Ad Astra Academy Scholarship'],
    livingCost: '€14,000-€17,000 / year (Dublin)',
    accommodation: 'UCD Residences €8,000-€13,000/year.',
    visaDetails:
      'Long Stay D visa required. Third Level Graduate Scheme allows 2 years post-study work. Strong tech/pharma hiring in Dublin.',
    employmentRate: '92% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Business (Smurfit MBA)', 'Engineering', 'Veterinary Medicine', 'Agri-food'],
  },
  // ---- Singapore (1) ----
  {
    id: 'nus',
    name: 'National University of Singapore (NUS)',
    country: 'Singapore',
    ranking: 8,
    acceptanceRate: '5-7%',
    tuitionFees: 'SGD 38,200-SGD 60,800 / year (international undergraduate, varies by course)',
    scholarships: ['NUS Global Merit Scholarship', 'ASEAN Undergraduate Scholarship', 'Singapore International Graduate Award (SINGA)'],
    livingCost: 'SGD 18,000-SGD 24,000 / year',
    accommodation: 'On-campus residences SGD 8,000-SGD 14,000/year.',
    visaDetails:
      'Student’s Pass required. Tuition Grant reduces fees by ~50% but requires 3-year Singapore work bond. Employment Pass allows post-study work.',
    employmentRate: '95% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Engineering', 'Business (NUS MBA)', 'Data Science', 'Public Policy'],
  },
  {
    id: 'ntu',
    name: 'Nanyang Technological University (NTU)',
    country: 'Singapore',
    ranking: 15,
    acceptanceRate: '5-7%',
    tuitionFees: 'SGD 38,200-SGD 60,800 / year (international undergraduate)',
    scholarships: ['NTU University Scholarship', 'ASEAN Undergraduate Scholarship', 'SINGA (graduate)'],
    livingCost: 'SGD 17,000-SGD 22,000 / year',
    accommodation: 'On-campus housing guaranteed for first year; SGD 8,000-SGD 12,000/year.',
    visaDetails:
      'Student’s Pass required. Tuition Grant available with 3-year work bond. Employment Pass for post-study work.',
    employmentRate: '94% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Engineering', 'Business', 'Communication Studies', 'Medicine'],
  },
  // ---- Netherlands (2) ----
  {
    id: 'tudelft',
    name: 'Delft University of Technology (TU Delft)',
    country: 'Netherlands',
    ranking: 47,
    acceptanceRate: '30-40% (varies by programme)',
    tuitionFees: '€19,500-€21,500 / year (international undergraduate)',
    scholarships: ['Justus & Louise van Effen Excellence Scholarship', 'Erasmus Mundus Scholarship', 'Holland Scholarship'],
    livingCost: '€15,000-€18,000 / year',
    accommodation: 'Student housing €6,000-€10,000/year.',
    visaDetails:
      'Entry Visa (MVV) and Residence Permit (VVR) required. Orientation Year (Zoekjaar) allows 1 year post-study job search. Highly Skilled Migrant permit for work.',
    employmentRate: '93% within 6 months of graduation',
    popularCourses: ['Aerospace Engineering', 'Computer Science', 'Mechanical Engineering', 'Architecture', 'Data Science'],
  },
  {
    id: 'amsterdam',
    name: 'University of Amsterdam (UvA)',
    country: 'Netherlands',
    ranking: 53,
    acceptanceRate: '20-30% (varies by programme)',
    tuitionFees: '€12,500-€17,500 / year (international undergraduate)',
    scholarships: ['Amsterdam Merit Scholarship', 'Holland Scholarship', 'Erasmus Mundus Scholarship'],
    livingCost: '€16,000-€20,000 / year (Amsterdam)',
    accommodation: 'UvA housing via SSH; €8,000-€14,000/year.',
    visaDetails:
      'Entry Visa (MVV) and Residence Permit required. Orientation Year (Zoekjaar) for 1-year post-study job search. Amsterdam is a tech hub with strong startup ecosystem.',
    employmentRate: '91% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Business (PPLE)', 'Economics', 'Psychology', 'Communication Science'],
  },
  // ---- Sweden (2) ----
  {
    id: 'kth',
    name: 'KTH Royal Institute of Technology',
    country: 'Sweden',
    ranking: 73,
    acceptanceRate: '15-25%',
    tuitionFees: 'SEK 155,000-SEK 295,000 / year (international undergraduate)',
    scholarships: ['KTH Scholarship', 'Swedish Institute Scholarship for Global Professionals', 'Erasmus Mundus'],
    livingCost: 'SEK 110,000-SEK 130,000 / year (Stockholm)',
    accommodation: 'Studentbostäder housing SEK 50,000-SEK 80,000/year.',
    visaDetails:
      'Residence Permit for Higher Education required. Proof of funds SEK 10,584/month. 12-month job-search permit after graduation. PR available after 4 years of work.',
    employmentRate: '92% within 6 months of graduation',
    popularCourses: ['Computer Science', 'Engineering', 'Machine Learning', 'Sustainable Technology', 'Industrial Design'],
  },
  {
    id: 'lund',
    name: 'Lund University',
    country: 'Sweden',
    ranking: 85,
    acceptanceRate: '20-30%',
    tuitionFees: 'SEK 110,000-SEK 245,000 / year (international undergraduate)',
    scholarships: ['Lund University Global Scholarship', 'Swedish Institute Scholarship', 'Erasmus Mundus'],
    livingCost: 'SEK 100,000-SEK 120,000 / year',
    accommodation: 'AF Bostäder and private SEK 45,000-SEK 70,000/year.',
    visaDetails:
      'Residence Permit for Higher Education required. 12-month job-search permit after graduation. Lund is a top European research university.',
    employmentRate: '90% within 6 months of graduation',
    popularCourses: ['Engineering', 'Physics', 'International Business', 'Biomedicine', 'Law'],
  },
];
